# Generated by Django 5.0.6 on 2024-07-07 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_timerecord_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
